#!/bin/sh

base_url="http://ftp.oldskool.org/pub/uwpuml/adventure/text_adventure/"
dest_folder="text_adventure"

mkdir "$dest_folder"
cd "$dest_folder"

echo '\n00-index.txt'; curl -o "00-index.txt" "${base_url}00-index.txt"
echo '\nabbey.zip'; curl -o "abbey.zip" "${base_url}abbey.zip"
echo '\nadv350.zip'; curl -o "adv350.zip" "${base_url}adv350.zip"
echo '\nadv660.zip'; curl -o "adv660.zip" "${base_url}adv660.zip"
echo '\nccr.zip'; curl -o "ccr.zip" "${base_url}ccr.zip"
echo '\ndeepspac.zip'; curl -o "deepspac.zip" "${base_url}deepspac.zip"
echo '\ndunjin43.zip'; curl -o "dunjin43.zip" "${base_url}dunjin43.zip"
echo '\nec3.zip'; curl -o "ec3.zip" "${base_url}ec3.zip"
echo '\nhumbug.zip'; curl -o "humbug.zip" "${base_url}humbug.zip"
echo '\njim.zip'; curl -o "jim.zip" "${base_url}jim.zip"
echo '\nmajik.zip'; curl -o "majik.zip" "${base_url}majik.zip"
echo '\nmanor.zip'; curl -o "manor.zip" "${base_url}manor.zip"
echo '\npcadvent.zip'; curl -o "pcadvent.zip" "${base_url}pcadvent.zip"
echo '\npcdungeo.zip'; curl -o "pcdungeo.zip" "${base_url}pcdungeo.zip"
echo '\npcworld.zip'; curl -o "pcworld.zip" "${base_url}pcworld.zip"
echo '\nralf.zip'; curl -o "ralf.zip" "${base_url}ralf.zip"
echo '\nskyland.zip'; curl -o "skyland.zip" "${base_url}skyland.zip"
echo '\ntads2doc.zip'; curl -o "tads2doc.zip" "${base_url}tads2doc.zip"
echo '\ntads2exe.zip'; curl -o "tads2exe.zip" "${base_url}tads2exe.zip"
echo '\ntrilogy.zip'; curl -o "trilogy.zip" "${base_url}trilogy.zip"
echo '\ntzero.zip'; curl -o "tzero.zip" "${base_url}tzero.zip"
echo '\nunnk1v30.zip'; curl -o "unnk1v30.zip" "${base_url}unnk1v30.zip"
echo '\nunnk2v30.zip'; curl -o "unnk2v30.zip" "${base_url}unnk2v30.zip"

{
  printf '%-20s %s\n' "abbey.zip" "Abbey"
  printf '%-20s %s\n' "adv350.zip" "Adventure"
  printf '%-20s %s\n' "adv660.zip" "Adventure II"
  printf '%-20s %s\n' "ccr.zip" "Colossal Cave Revisited"
  printf '%-20s %s\n' "deepspac.zip" "Deep Space Drifter"
  printf '%-20s %s\n' "dunjin43.zip" "Dunjin"
  printf '%-20s %s\n' "ec3.zip" "Enchanted Castle"
  printf '%-20s %s\n' "humbug.zip" "Humbug"
  printf '%-20s %s\n' "jim.zip" "Jacaranda Jim"
  printf '%-20s %s\n' "majik.zip" "Majik"
  printf '%-20s %s\n' "manor.zip" "Hampton Manor"
  printf '%-20s %s\n' "pcadvent.zip" "Colossal Cave"
  printf '%-20s %s\n' "pcdungeo.zip" "Dungeon"
  printf '%-20s %s\n' "pcworld.zip" "World"
  printf '%-20s %s\n' "ralf.zip" "Castle Ralf"
  printf '%-20s %s\n' "skyland.zip" "Skyland's Star"
  printf '%-20s %s\n' "tads2doc.zip" "Documentation for TADS 2"
  printf '%-20s %s\n' "tads2exe.zip" "TADS 2"
  printf '%-20s %s\n' "trilogy.zip" "Droppy & Pru Trilogy"
  printf '%-20s %s\n' "tzero.zip" "T-Zero"
  printf '%-20s %s\n' "unnk1v30.zip" "Unnkulian Adventures"
  printf '%-20s %s\n' "unnk2v30.zip" "Unnkulian Adventures II"
} > __files.txt