#!/bin/sh

base_url="http://ftp.oldskool.org/pub/drivers/unsorted/misc/VOL1/"
dest_folder="vol1"

mkdir "$dest_folder"
cd "$dest_folder"

echo '\n1.IMD'; curl -o '1.IMD' "${base_url}1.IMD"
echo '\n2.IMD'; curl -o '2.IMD' "${base_url}2.IMD"
echo '\n3.IMD'; curl -o '3.IMD' "${base_url}3.IMD"
echo '\n4.IMD'; curl -o '4.IMD' "${base_url}4.IMD"
echo '\n5.IMD'; curl -o '5.IMD' "${base_url}5.IMD"
echo '\n6.IMD'; curl -o '6.IMD' "${base_url}6.IMD"
echo '\n7.IMD'; curl -o '7.IMD' "${base_url}7.IMD"
echo '\n8.IMD'; curl -o '8.IMD' "${base_url}8.IMD"
echo '\n9.IMD'; curl -o '9.IMD' "${base_url}9.IMD"
echo '\n10.IMD'; curl -o '10.IMD' "${base_url}10.IMD"
echo '\n11.IMD'; curl -o '11.IMD' "${base_url}11.IMD"
echo '\n12.IMD'; curl -o '12.IMD' "${base_url}12.IMD"
echo '\n13.IMD'; curl -o '13.IMD' "${base_url}13.IMD"
echo '\n14.IMD'; curl -o '14.IMD' "${base_url}14.IMD"
echo '\n15.IMD'; curl -o '15.IMD' "${base_url}15.IMD"
echo '\n16.IMD'; curl -o '16.IMD' "${base_url}16.IMD"
echo '\n17.IMD'; curl -o '17.IMD' "${base_url}17.IMD"
echo '\n18.IMD'; curl -o '18.IMD' "${base_url}18.IMD"
echo '\n19.IMD'; curl -o '19.IMD' "${base_url}19.IMD"
echo '\n20.IMD'; curl -o '20.IMD' "${base_url}20.IMD"
echo '\n21.IMD'; curl -o '21.IMD' "${base_url}21.IMD"
echo '\n22.IMD'; curl -o '22.IMD' "${base_url}22.IMD"
echo '\n23.IMD'; curl -o '23.IMD' "${base_url}23.IMD"
echo '\n24.IMD'; curl -o '24.IMD' "${base_url}24.IMD"
echo '\n25.IMD'; curl -o '25.IMD' "${base_url}25.IMD"
echo '\n26.IMD'; curl -o '26.IMD' "${base_url}26.IMD"
echo '\n27.IMD'; curl -o '27.IMD' "${base_url}27.IMD"
echo '\n28.IMD'; curl -o '28.IMD' "${base_url}28.IMD"
echo '\n29.IMD'; curl -o '29.IMD' "${base_url}29.IMD"
echo '\n30.IMD'; curl -o '30.IMD' "${base_url}30.IMD"
echo '\nVOL1.TXT'; curl -o 'VOL1.TXT' "${base_url}VOL1.TXT"
